name: Actions Workflow

on:
  - push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: hello-world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Tom
      - name: Log Greeting Time
        run: echo "${{ steps.hello-world.outputs.time }}"