name: Container
on: push

jobs:


  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.22-alpine
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker (Hello world)
        uses: docker://node:12.9-alpine
        with:
          entrypoint: /bin/echo
          args: Hello World
      - name: Step with docker (Log node version)
        uses: docker://node:12.9-alpine
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Step with docker (Run a script)
        uses: docker://node:12.9-alpine
        with:
          entrypoint: ./script.sh
          args: "Some string"

  node-docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'X'
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"Tom\", \"address\": \"Leicester\"}'"
      - name: Get users
        run: curl http://localhost:3001/api/users

